package com.myspace.ticket;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SolutionORM implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SOLUTIONORM_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "SOLUTIONORM_ID_GENERATOR", sequenceName = "SOLUTIONORM_ID_SEQ")
    private java.lang.Long id;

    public SolutionORM() {
    }
    
    public SolutionORM(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}